version: 2.1

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack 
          command: aws cloudformation create-stack --stack-name myStack1 --template-body file://Infra.yml --region us-east-1

  get_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Get Infrastructure IPs in Inventory 
          command: echo "[all]" > inventory ; aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> inventory


  config_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints: ["66:73:15:e4:c7:eb:60:9f:a2:34:c8:2a:6d:b7:e4:b6"] 
      - run:
          name: Install Ansible
          command: apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: ansible-playbook -i inventory playbook.yml 
 

workflows:
  main:
    jobs:
      - create_infrastructure
      - get_infrastructure:
          requires: 
              - create_infrastructure
      - config_infrastructure:
          requires: 
              - get_infrastructure